# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 23:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditor', to=settings.AUTH_USER_MODEL, verbose_name='Creditor')),
                ('debitors', models.ManyToManyField(related_name='Debitors', to=settings.AUTH_USER_MODEL, verbose_name='Debitors')),
            ],
        ),
    ]
