# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fineants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
